# Generated by Django 5.2.8 on 2026-01-15 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='data_publicacao',
            field=models.DateField(default='2026-01-14'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='noticia',
            name='municipio',
            field=models.CharField(default='2026-01-14', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='noticia',
            name='visualizacoes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
