# Generated by Django 5.2.8 on 2026-01-15 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_noticia_data_publicacao_noticia_municipio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='visualizacoes',
        ),
    ]
