# Generated by Django 5.2.8 on 2026-01-15 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_remove_noticia_visualizacoes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='data_publicacao',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='municipio',
        ),
    ]
