# Generated by Django 5.2.8 on 2026-01-19 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0004_remove_noticia_data_publicacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='acessos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='noticia',
            name='validada',
            field=models.BooleanField(default=False),
        ),
    ]
