# Generated by Django 5.2.8 on 2026-01-20 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0005_noticia_acessos_noticia_validada'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='acessos',
            new_name='visualizacoes',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='validada',
        ),
        migrations.AlterField(
            model_name='noticia',
            name='confiavel',
            field=models.BooleanField(null=True),
        ),
    ]
