# Generated by Django 5.2.8 on 2025-12-21 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='perfil',
            field=models.CharField(choices=[('estagiario', 'Estagiário'), ('reporter', 'Repórter'), ('admin', 'Administrador')], default='estagiario', max_length=20),
        ),
    ]
